# For more information: https://laravel.com/docs/d9
version: "3"
services:
    ## web service #######################################################################################################
    web:
        build:
            context: ./docker/web
            args:
                WWWGROUP: "${WWWGROUP}"
                WWWUSER: "${WWWUSER}"
                PHP_VERSION: "${PHP_VERSION}"
                INSTALL_XDEBUG: "${INSTALL_XDEBUG}"
                DEFAULT_WEB_SERVER: "${DEFAULT_WEB_SERVER}"
                APP_ENV: "${APP_ENV}"
        networks:
            - d9
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "${PROJECT_ROOT}:/var/www/html"
            - "${VENDOR_ROOT}:/var/www/html/vendor"
            - "${PHP_LOCAL_CONFIG}:/etc/php/${PHP_VERSION}/${PHP_CONFIG_FOLDER}/conf.d/override_php.ini"
            - "${MSMTP_LOCAL_CONFIG}:/etc/msmtprc"
        depends_on:
            - db
            - redis
        container_name: ${WEB_CONTAINER_NAME}
    ### hostmachine ######################################################################################################
    hostmachine:
        image: qoomon/docker-host
        cap_add: ["NET_ADMIN", "NET_RAW"]
        deploy:
            resources:
                limits:
                    memory: 8M
        restart: on-failure
        networks:
            - d9
        container_name: ${HOSTMACHINE_CONTAINER_NAME}
    ### composer #########################################################################################################
    composer:
        build:
            context: ./docker/composer/
        working_dir: /var/www/html/
        volumes:
            - "./:/var/www/html"
        user: "${WWWUSER}"
        networks:
            - d9
        container_name: ${COMPOSER_CONTAINER_NAME}
    ## mariadb service #####################################################################################################################
    ### database #########################################################################################################
    db:
        image: "${DB_IMAGE}:${DB_VERSION}"
        restart: "always"
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_ROOT_USER: "${DB_USERNAME}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - "d9_db:/var/lib/mysql"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
        networks:
            - d9
        container_name: ${DB_CONTAINER_NAME}
    ## redis service #####################################################################################################
    redis:
        image: "redis:alpine"
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - "d9_redis:/data"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
        networks:
            - d9
        container_name: ${REDIS_CONTAINER_NAME}
    ## mailhog service ###################################################################################################
    mailhog:
        image: "mailhog/mailhog:latest"
        ports:
            - "${FORWARD_MAILHOG_PORT:-1025}:1025"
            - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025"
        networks:
            - d9
        container_name: ${MAIL_SERVICE_CONTAINER_NAME}
################################################################################################################################
networks:
    d9:
        driver: bridge
volumes:
    d9_db:
        driver: local
    d9_redis:
        driver: local
